#!/usr/bin/env bash

pushd "$(dirname -- $0)" > /dev/null

mkdir -p scans
mkdir -p site

for config in configs/*.yaml
do
    site="$(basename ${config/.yaml/})"
    echo "Scan $site"
    ./scan "$site" &
done

popd > /dev/null