#!/usr/bin/env bash

export DIR="$(dirname -- "$0")"
config="$1"

site="$(basename ${config/.yaml/})"
php to_XML.php "$config" > "$DIR/site/$site.xml"
xsltproc nmap_cmd.xsl "$DIR/site/$site.xml" | sh
mv "$DIR/scans/$site.xml.tmp" "$DIR/scans/$site.xml"